version: '2.1'

networks:
  iot-devices:
    driver: bridge

services:
  sensorrequest:
    image: sensorrequest:v0.2.0
    build:
      context: .
      dockerfile: ./sensorrequest.Dockerfile
    depends_on:
      counterfit:
        condition: service_started
    networks:
      - iot-devices

  counterfit:
    image: counterfit:v0.1.4.dev6
    build:
      context: .
      dockerfile: ./counterfit.Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - iot-devices
